### ISSUE TITLE
Save diagram problem

### ISSUE THREAD

**Issue by zicka** [alexgheorghiu/diagramo-old#5]
check box public/private don't work, diagrams are always public.

**Comment by zicka** [comment]
found solution:
file: controler.php
line:564

$diagram->public = (isset($_REQUEST['public']) && $_REQUEST['public'] == 'true') ? 'true' : 'false';

changed to

$diagram->public = (isset($_REQUEST['public']) && $_REQUEST['public'] == 'true') ? 1 : 0;

**Comment by alexgheorghiu** [comment]
I'll take a look and add your code if works

**Comment by alexgheorghiu** [comment]
You were right. Fixed on sources.

**Comment by alexgheorghiu** [comment]
Hi I want to inform you that the project was "(re)moved" to  https://github.com/alexgheorghiu/diagramo
Please follow it there and add issues there.

Thanks for support "zicka" :)
