### ISSUE TITLE
Is path creating algorithm your own algorithm or not?

### ISSUE THREAD

**Issue by bhaarata** [alexgheorghiu/diagramo-old#9]
At first I would like to thank you for sharing your source code!

And I would like to ask you about the algorithm for path creating between 2 draggable points. Is it your own algorithm in your solution or is it from some book or from page in internet? I have never seen something like this and if it is the second case (not your own algorithm), I would like to read a litle bit more about this algorithm.

Would you like to give me some link(s) or names for this algorithm?

Thank you again!

**Comment by alexgheorghiu** [comment]
It was my own algorithm :)
